# Copyright (c) The ThingSet Project Contributors
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: thingset
      url-base: https://github.com/ThingSet
    - name: libresolar
      url-base: https://github.com/LibreSolar
  projects:
    - name: zephyr
      # libresolar fork includes https://github.com/zephyrproject-rtos/zephyr/pull/51327
      remote: libresolar
      revision: v3.2-branch
      import:
        name-allowlist:
          - cmsis
          - edtt
          - hal_espressif
          - hal_stm32
          - hal_st
          - loramac-node
          - mbedtls
          - tinycrypt
    - name: thingset-device-library
      remote: thingset
      revision: 9630a357de071ac63bfbbaf9d91c6c937663601f
      path: modules/thingset
